name: ci

on: [push, pull_request]


jobs:

  frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Check out code
      uses: actions/checkout@v2
    - run: mkdir -p dist/css && touch dist/css/1
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: frontend # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: dist


  docker:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: frontend
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        # Artifact name
        name: frontend # optional
        path: dist 
    - run: find . 
